// <auto-generated />
using System;
using InsureZenAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InsureZenAPI.Migrations
{
    [DbContext(typeof(InsureZenContext))]
    [Migration("20260418074945_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InsureZenAPI.Models.Claim", b =>
                {
                    b.Property<Guid>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedClaimData")
                        .HasColumnType("text");

                    b.Property<string>("RawClaimData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ClaimId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("InsureZenAPI.Models.InsuranceCompany", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CompanyId");

                    b.ToTable("InsuranceCompanies");
                });

            modelBuilder.Entity("InsureZenAPI.Models.Review", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CheckerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CheckerSubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid");

                    b.Property<int?>("FinalDecision")
                        .HasColumnType("integer");

                    b.Property<string>("MakerFeedback")
                        .HasColumnType("text");

                    b.Property<Guid>("MakerId")
                        .HasColumnType("uuid");

                    b.Property<int>("MakerRecommendation")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MakerSubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ReviewId");

                    b.HasIndex("ClaimId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("InsureZenAPI.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InsureZenAPI.Models.Claim", b =>
                {
                    b.HasOne("InsureZenAPI.Models.InsuranceCompany", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("InsureZenAPI.Models.Review", b =>
                {
                    b.HasOne("InsureZenAPI.Models.Claim", "Claim")
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });
#pragma warning restore 612, 618
        }
    }
}
